// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	redis2 "github.com/redis/go-redis/v9"
	"go-clean-architecture/config"
	"go-clean-architecture/internal/application/user"
	"go-clean-architecture/internal/delivery/grpc"
	"go-clean-architecture/internal/delivery/http"
	"go-clean-architecture/internal/delivery/http/v1"
	"go-clean-architecture/internal/delivery/websocket"
	"go-clean-architecture/internal/infrastructure/persistence/postgres"
	"go-clean-architecture/internal/infrastructure/persistence/redis"
	"go-clean-architecture/internal/pkg/logger"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := postgres.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	unitOfWork := postgres.NewGormUoW(db)
	repository := postgres.NewUserRepository(db)
	createUserUseCase := user.NewCreateUserUseCase(unitOfWork, repository)
	getUserUseCase := user.NewGetUserUseCase(repository)
	userServiceServer := grpc.NewUserServiceServer(createUserUseCase, getUserUseCase)
	options := config.ProvideLoggerOptions(configConfig)
	zapLogger, err := logger.NewLogger(options)
	if err != nil {
		return nil, err
	}
	grpcServer := grpc.NewGRPCServer(userServiceServer, zapLogger)
	hub := websocket.NewHub(zapLogger)
	userHandler := v1.NewUserHandler(createUserUseCase, getUserUseCase)
	engine := http.RegisterRoutes(userHandler, zapLogger)
	client, err := redis.NewRedisClient(configConfig)
	if err != nil {
		return nil, err
	}
	app := NewApp(grpcServer, hub, engine, db, client, zapLogger)
	return app, nil
}

// wire.go:

type App struct {
	GRPCSrv *grpc.GRPCServer
	WSHub   *websocket.Hub
	Router  *gin.Engine
	DB      *gorm.DB
	Redis   *redis2.Client
	Logger  *zap.Logger
}

func NewApp(grpcSrv *grpc.GRPCServer, wsHub *websocket.Hub, router *gin.Engine, db *gorm.DB, rdb *redis2.Client, logger2 *zap.Logger) *App {
	return &App{
		GRPCSrv: grpcSrv,
		WSHub:   wsHub,
		Router:  router,
		DB:      db,
		Redis:   rdb,
		Logger:  logger2,
	}
}
